blueprint:
  name: "LIFX Morph: Temperature Based Color Thermometer"
  description: "Changes a LIFX light's morph effect palette based on a temperature sensor's value."
  domain: automation
  input:
    temp_sensor:
      name: Temperature Sensor
      description: The sensor that provides the temperature.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_light:
      name: LIFX Light
      description: The LIFX light to apply the morph effect to.
      selector:
        entity:
          domain: light
          integration: lifx
    brightness:
      name: Brightness
      description: Brightness percentage for the effect.
      default: 60
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

mode: restart

trigger:
  - platform: state
    entity_id: !input temp_sensor

condition:
  - condition: template
    value_template: "{{ is_state(target_light, 'on') }}"

action:
  - variables:
      # Map the inputs to variables for use in templates
      target_light: !input target_light
      brightness_pct: !input brightness
      temp: "{{ states(temp_sensor) | float(0) }}"
      temp_sensor: !input temp_sensor
      
      # Your core logic for color mapping
      current_mid: >
        {% if temp <= 0 %} [0, 0] {% elif temp <= 3 %} [280, 7] {% elif temp <= 6 %} [281, 18] 
        {% elif temp <= 9 %} [282, 32] {% elif temp <= 12 %} [283, 47] {% elif temp <= 15 %} [284, 62] 
        {% elif temp <= 18 %} [285, 78] {% elif temp <= 21 %} [286, 79] {% elif temp <= 24 %} [287, 81] 
        {% elif temp <= 27 %} [288, 83] {% elif temp <= 30 %} [289, 86] {% elif temp <= 33 %} [300, 100] 
        {% elif temp <= 36 %} [210, 26] {% elif temp <= 39 %} [204, 70] {% elif temp <= 42 %} [204, 76] 
        {% elif temp <= 45 %} [204, 76] {% elif temp <= 48 %} [204, 76] {% elif temp <= 51 %} [168, 86] 
        {% elif temp <= 54 %} [145, 78] {% elif temp <= 57 %} [145, 77] {% elif temp <= 60 %} [145, 78] 
        {% elif temp <= 63 %} [145, 77] {% elif temp <= 66 %} [145, 42] {% elif temp <= 69 %} [145, 27] 
        {% elif temp <= 72 %} [48, 75] {% elif temp <= 75 %} [48, 55] {% elif temp <= 78 %} [37, 54] 
        {% elif temp <= 81 %} [37, 73] {% elif temp <= 84 %} [28, 68] {% elif temp <= 87 %} [28, 85] 
        {% elif temp <= 90 %} [24, 100] {% elif temp <= 93 %} [24, 55] {% elif temp <= 96 %} [24, 35] 
        {% elif temp <= 99 %} [6, 40] {% elif temp <= 102 %} [6, 58] {% elif temp <= 105 %} [6, 74] 
        {% elif temp <= 108 %} [6, 69] {% elif temp <= 111 %} [6, 74] {% elif temp <= 114 %} [6, 74] 
        {% elif temp <= 117 %} [6, 77] {% else %} [6, 78] {% endif %}
      
      higher: "[{{ (current_mid[0] + 20) % 360 }}, {{ current_mid[1] }}]"
      lower: "[{{ (current_mid[0] - 20) % 360 }}, {{ current_mid[1] }}]"

  - action: lifx.effect_morph
    data:
      speed: 2
      power_on: true
      palette: >
        {% set c_mid = current_mid if current_mid is list else from_json(current_mid) %} 
        {% set c_high = higher if higher is list else from_json(higher) %} 
        {% set c_low = lower if lower is list else from_json(lower) %}
        {% set colors = [c_high, c_mid, c_mid, c_low] %} 
        {% set ns = namespace(hsbk=[]) %} 
        {% for c in colors %}
          {% set ns.hsbk = ns.hsbk + [[c[0], c[1], brightness_pct, 3500]] %}
        {% endfor %} 
        {{ ns.hsbk }}
    target:
      entity_id: !input target_light