blueprint:
  name: "LIFX Color Morphing Temperature Thermometer"
  description: "Subtle color shifting thermometer for LIFX devices with zones."
  domain: automation
  input:
    temp_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_light: 
      name: LIFX Light
      selector:
        entity:
          domain: light
          integration: lifx
    brightness:
      name: Brightness
      default: 60
      selector:
        number:
          min: 1
          max: 100

mode: restart

trigger:
  - platform: state
    entity_id: !input temp_sensor

condition:
  - condition: template
    value_template: "{{ is_state(target_light, 'on') }}"
    # We define target_light below in variables to make this work

action:
  - variables:
      # This is the critical part: mapping the !input to a usable variable
      temp_sensor_entity: !input temp_sensor
      target_light: !input target_light
      brightness_val: !input brightness
      
      # Now we use the variable name 'temp_sensor_entity' instead of the raw input
      temp: "{{ states(temp_sensor_entity) | float(0) }}"
      
      color_data: >
        {% if temp <= 0 %} [0, 0] {% elif temp <= 3 %} [280, 7] {% elif temp <= 6 %} [281, 18] 
        {% elif temp <= 9 %} [282, 32] {% elif temp <= 12 %} [283, 47] {% elif temp <= 15 %} [284, 62] 
        {% elif temp <= 18 %} [285, 78] {% elif temp <= 21 %} [286, 79] {% elif temp <= 24 %} [287, 81] 
        {% elif temp <= 27 %} [288, 83] {% elif temp <= 30 %} [289, 86] {% elif temp <= 33 %} [300, 100] 
        {% elif temp <= 36 %} [210, 26] {% elif temp <= 39 %} [204, 70] {% elif temp <= 42 %} [204, 76] 
        {% elif temp <= 45 %} [204, 76] {% elif temp <= 48 %} [204, 76] {% elif temp <= 51 %} [168, 86] 
        {% elif temp <= 54 %} [145, 78] {% elif temp <= 57 %} [145, 77] {% elif temp <= 60 %} [145, 78] 
        {% elif temp <= 63 %} [145, 77] {% elif temp <= 66 %} [145, 42] {% elif temp <= 69 %} [145, 27] 
        {% elif temp <= 72 %} [48, 75] {% elif temp <= 75 %} [48, 55] {% elif temp <= 78 %} [37, 54] 
        {% elif temp <= 81 %} [37, 73] {% elif temp <= 84 %} [28, 68] {% elif temp <= 87 %} [28, 85] 
        {% elif temp <= 90 %} [24, 100] {% elif temp <= 93 %} [24, 55] {% elif temp <= 96 %} [24, 35] 
        {% elif temp <= 99 %} [6, 40] {% elif temp <= 102 %} [6, 58] {% elif temp <= 105 %} [6, 74] 
        {% elif temp <= 108 %} [6, 69] {% elif temp <= 111 %} [6, 74] {% elif temp <= 114 %} [6, 74] 
        {% elif temp <= 117 %} [6, 77] {% else %} [6, 78] {% endif %}

  - action: lifx.effect_morph
    data:
      speed: 2
      power_on: true
      palette: >
        {% set mid = color_data if color_data is list else from_json(color_data) %}
        {% set h = mid[0] | int %}
        {% set s = mid[1] | int %}
        {% set b = brightness_val | int %}
        [
          [{{ (h + 20) % 360 }}, {{ s }}, {{ b }}, 3500],
          [{{ h }}, {{ s }}, {{ b }}, 3500],
          [{{ h }}, {{ s }}, {{ b }}, 3500],
          [{{ (h - 20) % 360 }}, {{ s }}, {{ b }}, 3500]
        ]
    target:
      entity_id: !input target_light